version: 2.1
orbs:
  slack: circleci/slack@5.0.0
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Compilar script Bash - Verificar número primo"
          command: |
            chmod +x scripts/is_prime.sh
            ./scripts/is_prime.sh 0 > result.txt
      - run:
          name: "Verificar salida del script"
          command: cat result.txt

  test:
    docker:
      - image: bats/bats:latest
    steps:
      - checkout
      - run:
          name: "Ejecutar pruebas con bats"
          command: bats tests/test_script.bats
  notify_success:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "La ejecución se realizó correctamente",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

  notify_failure:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "La ejecución se realizó correctamente",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - notify_success:
          context: slack-secrets
          requires:
            - build
            - test
          filters:
            branches:
              only: main
          when: on_success
      - notify_failure:
          context: slack-secrets
          requires:
            - build
            - test
          filters:
            branches:
              only: main
          when: on_failure
